### PR TITLE
Fix/disabled record event

### LINKED ISSUE #30: Toolbar.record_event/2 does not pass through callback result when toolbar is disabled
When toolbar is disabled with the rest of installation configs in place (templates in this case), it raises on template render:

```
Request: GET /
** (exit) an exception was raised:
    ** (FunctionClauseError) no function clause matching in Phoenix.Template.HTML.encode_to_iodata!/1
        (phoenix) lib/phoenix/template/html.ex:12: Phoenix.Template.HTML.encode_to_iodata!({:error, :toolbar_disabled})
        (sylar) lib/sylar/endpoint.ex:1: Sylar.Endpoint.instrument/4
        (phoenix) lib/phoenix/controller.ex:646: Phoenix.Controller.do_render/4
        (sylar) web/controllers/home_controller.ex:1: Sylar.HomeController.action/2
        (sylar) web/controllers/home_controller.ex:1: Sylar.HomeController.phoenix_controller_pipeline/2
        (sylar) lib/sylar/endpoint.ex:1: Sylar.Endpoint.instrument/4
        (sylar) lib/phoenix/router.ex:261: Sylar.Router.dispatch/2
        (sylar) web/router.ex:1: Sylar.Router.do_call/2
        (sylar) lib/sylar/endpoint.ex:1: Sylar.Endpoint.phoenix_pipeline/1
        (sylar) lib/sylar/endpoint.ex:42: Sylar.Endpoint."call (overridable 2)"/2
        (sylar) lib/sylar/endpoint.ex:42: Sylar.Endpoint."call (overridable 3)"/2
        (sylar) lib/plug/debugger.ex:123: Sylar.Endpoint."call (overridable 4)"/2
        (sylar) lib/sylar/endpoint.ex:1: Sylar.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/bmikhayl/Projects/sylar/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

### PR DESCRIPTION
**Pull request by kagux**
fixes #30

---
This change is [Reviewable](https://reviewable.io/reviews/kagux/ex_debug_toolbar/37)

### CODE REVIEW

File: lib/ex_debug_toolbar.ex [hunk 1]
```diff
@@ -112,7 +112,6 @@ defmodule ExDebugToolbar do
   Returns `func` return value.
   """
   @spec record_event(id, String.t(), function()) :: any()
-  @decorate noop_when_toolbar_disabled()
```
Comment (epilgrim) [inline lib/ex_debug_toolbar.ex]: how is re-enabling this helping?

Comment (kagux) [inline lib/ex_debug_toolbar.ex]: wrapped function gets executed and results are correctly returned from this call, while toolbar related functions that wrap are still noop.

Comment (epilgrim) [inline lib/ex_debug_toolbar.ex]: ahh, right, so start_event and finish_event are noop by themselves. 
makes sense
